BookStore/src/BookStore/Controllers/BooksController.cs
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Mvc;

namespace BookStore.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }

        // GET: Book/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // GET: Book/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return this.HttpNotFound();
            }
            
            return this.View(id);
        }
    }
}

BookStore/src/BookStore/Controllers/CategoriesController.cs
using Microsoft.AspNet.Mvc;

namespace BookStore.Controllers
{
    public class CategoriesController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }

        // GET: Category/Create
        public IActionResult Create()
        {
            return this.View();
        }

        // GET: Category/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return this.HttpNotFound();
            }
            
            return this.View(id);
        }
    }
}

BookStore/src/BookStore/Controllers/ReportsController.cs
using Microsoft.AspNet.Mvc;

namespace BookStore.Controllers
{
    public class ReportsController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }
    }
}

BookStore/src/BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">BookStore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Books" asp-action="Index">Books</a></li>
                    <li><a asp-controller="Categories" asp-action="Index">Categories</a></li>
                    <li><a asp-controller="Reports" asp-action="Index">Report</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>   
    <script src="~/lib/knockout.js/knockout.js"></script>

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>